### ISSUE TITLE
Gradle Run Issue

### ISSUE THREAD

**Issue by jalexcole** [ambrosiogabe/MinimalLWJGLEngine#1]
```
 ~/Documents/Games/MinimalLWJGLEngine$ gradle run
 
 FAILURE: Build failed with an exception.
 
 * What went wrong:
 Task 'run' not found in root project 'mario'.
 
 * Try:
 Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 
 * Get more help at https://help.gradle.org
 
 Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
 Use '--warning-mode all' to show the individual deprecation warnings.
 See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings
 
 BUILD FAILED in 571ms
```
Build is on Ubuntu 20.04 LTS

**Comment by codingminecraft** [comment]
Hey Alex, it looks like this must be an issue with setting up IntelliJ and not necessarily Gradle. Every time I install an IntelliJ project from a Github repository I have to do some extra steps to get Gradle to work correctly, in this case it looks like it must think your project name is something weird. I would suggest just creating a fresh new IntelliJ (or Eclipse if that's what your using) project, and see if you can get Gradle to work with the fresh project. If you can then I would just copy all the source code files over and then it should be good. Let me know if it still gives you an error with a fresh project

**Comment by jalexcole** [comment]
Gabe,
So far all I gave done is run everything in the terminal. No IntelliJ setup.
`git clone https://github.com/ambrosiogabe/MinimalLWJGLEngine.git`
Then go into build.gradle and change 
`project.ext.lwjglNatives = "natives-windows"`
to
`project.ext.lwjglNatives = "natives-linux"`
This is followed with:
```~/Documents/Games/MinimalLWJGLEngine$ gradle build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 562ms
3 actionable tasks: 3 up-to-date
```
```~/Documents/Games/MinimalLWJGLEngine$ gradle run

FAILURE: Build failed with an exception.

* What went wrong:
Task 'run' not found in root project 'mario'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 491ms
```

**Comment by jalexcole** [comment]
Update:
The Runs in IDEA if pulled directly from github upon setup.

**Comment by jalexcole** [comment]
Issue seams to involve command line gradle not wanting to pull from dependencies to build the external library before building the java application.

**Comment by ambrosiogabe** [comment]
Hey Alex, once again I'm sorry that it took me so long to respond. I've just been very busy in life the past couple weeks with my job and everything. I need to start doing some testing on Linux with LWJGL and get my Java projects working properly in it. I'm glad you seem to have solved it though, if you have any other questions you can just email me or respond to this thread and I will try to respond in a timely manner.
